//
//  PinchAlbumRouter.swift
//  PinchNL
//
//  Created by Andre Nogueira on 09/03/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PinchAlbumRoutingLogic {
    func routeToPhotos()
}

protocol PinchAlbumDataPassing {
    var dataStore: PinchAlbumDataStore { get }
}

class PinchAlbumRouter: NSObject, PinchAlbumRoutingLogic, PinchAlbumDataPassing {
    
    weak var viewController: PinchAlbumViewController?
    var dataStore: PinchAlbumDataStore
    
    init(dataStore: PinchAlbumDataStore) {
        self.dataStore = dataStore
    }
    
    // MARK: Routing
    
    func routeToPhotos() {
        let factory = PinchPhotosFactory()
        let nextViewController = factory.setup()
        var nextDataStore = nextViewController.router.dataStore
        passDataToPhotos(source: dataStore, destination: &nextDataStore)
        navigateToPhotos(source: viewController, destination: nextViewController)
    }
    
    // MARK: Passing data

    func passDataToPhotos(source: PinchAlbumDataStore, destination: inout PinchPhotosDataStore) {
        destination.photoData = source.photoData
    }
    
    // MARK: Navigation

    func navigateToPhotos(source: PinchAlbumViewController?, destination: PinchPhotosViewController) {
        source?.show(destination, sender: source)
    }
}
