# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PinchNL-MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'Kingfisher', '~> 6.0'
  pod 'RealmSwift'
  # Pods for PinchNL-MVVM

end

target 'PinchNL-VIP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya'
  pod 'RealmSwift'
  pod 'Kingfisher', '~> 6.0'

  # Pods for PinchNL-VIP

end
