name: PinchNL
options:
    bundleIdPrefix: com.pinch
    createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
    indentWidth: 4 # indent by 4 spaces
    tabWidth: 4 # a tab is 4 spaces
configs:
    Debug: debug
    integ: debug
    test: debug
    Release: release
targets:
    PinchNL-MVVM:
        type: application
        platform: iOS
        deploymentTarget: "13.0"
        sources:
            - path: PinchNL-MVVM
            - path: PinchNL-Core
            - path: PinchNL-Views
            - path: PinchNL-Networking
            - path: PinchNL-Models

    PinchNL-VIP:
        type: application
        platform: iOS
        deploymentTarget: "13.0"
        sources:
            - path: PinchNL-VIP
            - path: PinchNL-Core
            - path: PinchNL-Views
            - path: PinchNL-Networking
            - path: PinchNL-Models

schemes:
    PinchNL-MVVM:
        build:
            targets:
                PinchNL-MVVM: all
             
        run:
        config: Debug
        profile:
        config: Release
        analyze:
        config: Debug
        archive:
        config: Release
    
    PinchNL-VIP:
        build:
            targets:
                PinchNL-VIP: all
               
        run:
        config: Debug
        profile:
        config: Release
        analyze:
        config: Debug
        archive:
        config: Release
